name: Create Release Candidate

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    
env:
  JVM_OPTS: -Xmx4096m
  GRADLE_OPTS: |
        -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError
        -Dorg.gradle.caching=true
        -Dorg.gradle.configureondemand=true
        -Dkotlin.compiler.execution.strategy=in-process
        -Dkotlin.incremental=false  
        
jobs:
  dependencies:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Download sapmachine JDK 11
      run: |
        download_url="https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.14.1/sapmachine-jdk-11.0.14.1_linux-x64_bin.tar.gz"
        wget -O "${RUNNER_TEMP}/sapmachine-jdk-11.tar.gz" "${download_url}"
       
    - name: Setup sapmachine JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/sapmachine-jdk-11.tar.gz
        java-version: '11.0.14'
        architecture: x64    
        cache: 'gradle'

    - uses: maxim-lobanov/setup-android-tools@v1
      with:
        cache: true   
        
  quick_build_device_for_testers_signed:
    runs-on: ubuntu-latest
    needs: dependencies
     
    steps:
      - uses: actions/checkout@v3

      - name: Download sapmachine JDK 11
      run: |
        download_url="https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.14.1/sapmachine-jdk-11.0.14.1_linux-x64_bin.tar.gz"
        wget -O "${RUNNER_TEMP}/sapmachine-jdk-11.tar.gz" "${download_url}"

      - name: Setup sapmachine JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/sapmachine-jdk-11.tar.gz
        java-version: '11.0.14'
        architecture: x64    
        cache: 'gradle'

      - uses: maxim-lobanov/setup-android-tools@v1
      with:
        cache: true   
        
        
  firebase_screenshots:
    runs-on: ubuntu-latest
    needs: dependencies
     
    steps:
      - uses: actions/checkout@v3

      - name: Download sapmachine JDK 11
      run: |
        download_url="https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.14.1/sapmachine-jdk-11.0.14.1_linux-x64_bin.tar.gz"
        wget -O "${RUNNER_TEMP}/sapmachine-jdk-11.tar.gz" "${download_url}"

      - name: Setup sapmachine JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'jdkfile'
        jdkFile: ${{ runner.temp }}/sapmachine-jdk-11.tar.gz
        java-version: '11.0.14'
        architecture: x64    
        cache: 'gradle'

      - uses: maxim-lobanov/setup-android-tools@v1
      with:
        cache: true 
